import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen w-full gap-4 bg-gray-200 items-center justify-between p-4">
          <div className="flex text-white flex-col gap-4 w-[600px] px-4 py-10 py bg-emerald-400 min-h-[94vh] rounded-xl">
            <div className="bg-black/40 rounded-full p-2 w-full h-[300px]"></div>
            <span className="font-semibold text-3xl">Ionut</span>

            <div className="pt-12 flex flex-col">
              <span className="font-medium text-2xl">Income</span>
              <span className="font-medium text-2xl">Budget</span>
              <span className="font-medium text-2xl">Expenses</span>
              <span className="font-medium text-2xl">Savings</span>
            </div>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
